### ISSUE TITLE
Link "contact admin"

### ISSUE THREAD

**Issue by aangelot** [datatlas-erasme/datatlas#106]
_Test context_ : 
Thinkpad Ubuntu 22.04 15'
Mozilla Firefox 111.0.1 
Login Page

_Current behavior_ : 
When I click on "Contacter l'administrateur" it redirects to mailto:administrateur@metropole.fr

_Desired behavior_ : 
Redirect to mailto:aangelot@grandlyon.com

**Comment by OlivPi** [comment]
51c00a60368fd509472f400725af37dafdeea9f2
