### ISSUE TITLE
Correct footer

### ISSUE THREAD

**Issue by aangelot** [datatlas-erasme/datatlas#107]
Test context :
Thinkpad Ubuntu 22.04 15'
Mozilla Firefox 111.0.1
Login Page

Current behavior :
Logo of the Lyon Metropolis doesn't show. Same for the France Relance logo 

![Image](https://user-images.githubusercontent.com/33604381/227247632-6b503e72-3117-43e4-bf17-f9d3ec2f57ae.png)

Desired behavior :

- [x] #113
- [x] #114
- [x] Link behind datatlas logo : https://dev-datatlas.datagora.erasme.org/login 
- [x] Link behind Erasme logo : https://www.erasme.org/-Accueil-331- 
- [x] Link behind Lyon Metropolis logo : https://www.grandlyon.com/
- [x] Link behind France Relance logo : https://agence-cohesion-territoires.gouv.fr/france-relance-un-plan-de-cohesion-economique-sociale-et-territoriale-216 
- [x] Replace Lorem Ipsum with "Un projet mené par Erasme, laboratoire d'innovation de la Métropole de Lyon, avec le soutien de France Relance" 
- [x] Delete [© Datatlas]
- [x] #115

**Comment by OlivPi** [comment]
In my view, for the Lyon Metropole and France Relance logo, the problem come from the production environment. Everything is correct locally.

**Comment by lutangar** [comment]
> >  Show logo of Lyon Metropolis
> > Show logo of France Relance
>
> In my view, for the Lyon Metropole and France Relance logo, the problem come from the production environment.  Everything is correct locally.

@Pipazoul there's probably a static assets directory to serve somewhere, could you have a look ?

**Comment by Pipazoul** [comment]
On my side the logo are displayed in the deployed front, there are no static assets in those cases.
The Lyon and France Relance logo seem to have dedicated react component with svg encoded inside

ex : `apps/frontend/src/components/logos/FranceRelanceLogo.tsx` 

@aangelot Do you still have the same problem, if yes could you send the network/console logs from your browsers developper console ?

**Comment by aangelot** [comment]
@OlivPi => in render svg there is a "g" that should be removed
