### ISSUE TITLE
"A propos" menu

### ISSUE THREAD

**Issue by aangelot** [datatlas-erasme/datatlas#108]
Test context :
Thinkpad Ubuntu 22.04 15'
Mozilla Firefox 111.0.1
Login Page

Current behavior :
No margin between text and arrow : 
![Image](https://user-images.githubusercontent.com/33604381/227248543-7ccc5b3c-7c47-4380-8ae0-2c9c515e8702.png)
Arrow in the wrong direction 

Desired behavior :

- [x] Add a small margin between text and arrow (cf Figma) 
- [x] Inverse the direction of the arrows (cf Figma) 
- [x] Add text corresponding to the file https://docs.google.com/document/d/1u5iN6O5X9YlbmkaNp_4egLs5DwYvMScWRaxQJymhGEo/edit?usp=sharing

**Comment by OlivPi** [comment]
51c00a60368fd509472f400725af37dafdeea9f2
