### ISSUE TITLE
Layout issues

### ISSUE THREAD

**Issue by lutangar** [datatlas-erasme/datatlas#140]
- [x] Even for higher resolution in __Chrom*__ browsers there are always a vertical & horizontal scrollbar
    - [x] This triggers a map flickering, which, by changing the canvas resolution, trigger an infinite update loop oft he map state
- [x] Footer is too big !
![Screenshot from 2023-05-16 09-29-23](https://github.com/datatlas-erasme/datatlas/assets/568769/47e4788c-5538-48ee-86f1-7dc8d6df1426)

**Comment by aangelot** [comment]
Indeed, there are a few improvements to be made for responsiveness
