### ISSUE TITLE
Forms UX

### ISSUE THREAD

**Issue by lutangar** [datatlas-erasme/datatlas#141]
Form UX is too poor at the moment, there are no feedbacks : the user is blind during the few seconds of delay during the login process (Yeah  seconds, this is too way too long).
> *The same remarks applies more or less to "one button action" such as :*
> - delete a project (which doesn't requires any confirmation btw 😱 )
> - publish a project

Here are the list of feedbacks which might be expected :
- [x] Submit button must be greyed out during form submission to avoid reapeated submision
- [x] There should be a loader somewhere (was a local / global loading state design already ?)
- [x] Error messages are kind of ugly at the moment and should be styled
![Image](https://user-images.githubusercontent.com/568769/238569551-8695ee04-a7cf-41a9-a39b-472b64a899ef.png)
- [ ] When in error, an input style could change (red border for example)

**Comment by aangelot** [comment]
> _Submit button must be greyed out during form submission to avoid reapeated submision
There should be a loader somewhere (was a local / global loading state design already ?)_ 

It's related to #65 that answers perfectly these two issues

>  _Error messages are kind of ugly at the moment and should be styled_

I agree, not a priority so far but as we progress in experimentation I will ask a designer to make these minor changes

**Comment by lutangar** [comment]
After digging into this a bit, I think we need to settle a few things on the design system (button color, state, etc. ) before pushing further. 

I'm pretty sure we could discuss the details with @SeongHunChandra next week.

**Comment by SeongHunChandra** [comment]
Yes we shall 👍
