### ISSUE TITLE
Hide unimplemented features

### ISSUE THREAD

**Issue by lutangar** [datatlas-erasme/datatlas#142]
There are a few unimplemented which are apearring in the UI which should probably remain hidden for now :
- [x] "Voir tous >" (on projects page)
- [x] "Aide" & "Réglages" (in the topbar)
- [x] "Remember me" (on the login page)
- [ ] "Forgot password" (on the login page)
- [ ] ...

I'm sure I'm missing a few others as well..

**Comment by aangelot** [comment]
I totally agree, it would make it easier for the user to navigate
