### ISSUE TITLE
Can't access DatAtlas on my browser

### ISSUE THREAD

**Issue by aangelot** [datatlas-erasme/datatlas#200]
In my browser I cannot access DatAtlas (except in a private window) 

Error message : 

```
Oops! Unexpected Error

Something went wrong.

e.user is null 
```

If it occurs only for project team, not a priority

**Comment by lutangar** [comment]
This looks like a cache related issue, try to clean your storages.

**Comment by aangelot** [comment]
Ctrl + F5 wasn't enough but by cleaning the cookies everything runs perfectly thanks
