### ISSUE TITLE
Import data create an infinite number of layers

### ISSUE THREAD

**Issue by aangelot** [datatlas-erasme/datatlas#209]
Tested on Ubuntu, Firefox 

Ho to reproduce : 
1. Download the geoJSON of this dataset : https://data.grandlyon.com/jeux-de-donnees/producteurs-locaux-geolocalises-metropole-lyon/telechargements
2. Add this file to a project 
3. A huge number of layers are created (it looks like there is one layer by item in the dataset... but each layer contains all the items, there are all the same) 

See the result here https://dev-datatlas.datagora.erasme.org/projects/13

**Comment by aangelot** [comment]
Same error with other GeoJSON download from data.grandlyon

**Comment by lutangar** [comment]
> A huge number of layers are created (it looks like there is one layer by item in the dataset... but each layer contains all the items, there are all the same)

I think I saw this issue happening a few time, even on a "virgin" __Kepler__ project... 
Does it happens each time ?
Does it happens only with the file import feature or does it also happens with an URL import ?

> See the result here https://dev-datatlas.datagora.erasme.org/projects/13

I'm not seeing the result, I think it was linked with persistence issue #166 which is fixed and deployed.

**Comment by aangelot** [comment]
It happens each time with geoJSON from data.grandlyon... 
I tried with 5 different datasets (parks, body of waters, velovs...) 

That doesn't happen with an URL import, it just with upload

**Comment by lutangar** [comment]
As stated in #210 this also happens with a CSV import :

> Huge number of layers... with one point
> How to reproduce :

> Download CSV file of this dataset https://data.grandlyon.com/jeux-de-donnees/stations-velo-v-metropole-lyon/telechargements
> Import the CSV in a datatlas project
> A huge number of layers... with just one point and every time the same point

**Comment by aangelot** [comment]
The error doesn't occur with https://kepler.gl/demo so it may be corrected by KeplerV3 ? 

I have this message in the console : 

```
Uncaught (in promise) TypeError: a is undefined
    processFileContentUpdater vis-state-updaters.js:1572
    I index.js:2
    W Redux
    W index.js:27
    Redux 2
    p core.js:42
    h root.js:81
    h root.js:79
    m root.js:161
    Fv effects.ts:64
    d Redux
    eA history.ts:463
```

For CSV files, there is another problem that occurs with Kepler demo and I understood why : when you import a CSV from data.grandlyon, latitude and longitude are rounded : so we can see an unique point (4 ; 45). I create an issue about these rounded #221
