### ISSUE TITLE
Nothing happens when importing a CSV file

### ISSUE THREAD

**Issue by aangelot** [datatlas-erasme/datatlas#210]
**No response**
How to reproduce : 

1. Download CSV file of this dataset https://data.grandlyon.com/jeux-de-donnees/instances-marches-forains/telechargements 
2. Import the CSV in a datatlas project 
3. Nothing happens 

**Huge number of layers... with one point** 
How to reproduce : 

1. Download CSV file of this dataset https://data.grandlyon.com/jeux-de-donnees/stations-velo-v-metropole-lyon/telechargements 
2. Import the CSV in a datatlas project 
3. A huge number of layers... with just one point and every time the same point

**Comment by lutangar** [comment]
Related to #209

**Comment by aangelot** [comment]
The second behavior may be related to #209, is it also true for the first one ?

**Comment by lutangar** [comment]
You're right, the first behavior -- __Nothing happens__-- is probably not related, and there probably is a previous error which broke the app. 

Could you copy & paste the error message from the console when such behavior is happening ?


> Huge number of layers... with one point
