### ISSUE TITLE
Error while importing JSON

### ISSUE THREAD

**Issue by aangelot** [datatlas-erasme/datatlas#211]
How to reproduce : 

1. Download JSON file from datagrandlyon (from example this one : https://data.grandlyon.com/jeux-de-donnees/stations-velo-v-metropole-lyon/telechargements)
2. Upload it into a datatlas project 
3. Many errors messages appear 

![Image](https://github.com/datatlas-erasme/datatlas/assets/33604381/adc4daa5-8c19-4cc8-a0a2-f143cd2402c3)

Desired behavior : 
One error is enough (the mutlplication of error messages may be related to #209 )
Or the error comes from Datatlas, try to correct it
Or the error comes from the dataset, show a more explicit message

**Comment by lutangar** [comment]
I thought the `json` wasn't supported. 🤔 

Could you please create a separate issue for the multiple error messages ?

**Comment by aangelot** [comment]
Indeed JSON was'nt supported. I got cheated by this message : 


![Image](https://github.com/datatlas-erasme/datatlas/assets/33604381/a7b2444a-d3e1-49d7-befc-d59e3ef77dfc)


But in the Kepler documentation it's said that only csv, geoJSON and Kepler JSON are allowed. 

So I suggest : to change the message for the import (related to #208 ) 
Multiple error messages may be link to the #209 don't you say ? If yes, we can close the issue

**Comment by lutangar** [comment]
> Multiple error messages may be link to the https://github.com/datatlas-erasme/datatlas/issues/209 don't you say ? If yes, we can close the issue

 Maybe, but this is still a UI/UX issue, so let's reqaulify this issue.

About the message, yes, let's move this part of the issue to #208
