### ISSUE TITLE
Error while important data with an URL from data.grandlyon

### ISSUE THREAD

**Issue by aangelot** [datatlas-erasme/datatlas#212]
How to reproduce : 

Ubuntu, Firefox 
1. Choose a dataset in data.grandlyon (for example https://data.grandlyon.com/jeux-de-donnees/cinemas-metropole-lyon/api)
2. Try to import thanks to the web service CSV or JSON (for example with this link for csv : https://download.data.grandlyon.com/ws/grandlyon/adr_voie_lieu.adrcinema/all.csv?maxfeatures=100&start=1) 
3. An error appears, not explicit : it's just the URL of the dataset

Desired behavior : 
Or the error comes from the link or the dataset : explains the error 
Or the error comes from datatlas, try to correct it

**Comment by aangelot** [comment]
Cf #24 for the error message if the URL is incorrect

**Comment by lutangar** [comment]
The feature was initially described in #25 and a partial implementation was done in #70 which only support __GeoJson__ as of now.

Shall we implement `json` and `csv` format URL import or shall we only just say we support GeoJson for now ?
If so could you please create dedicated issues and set their priority ?

**Comment by aangelot** [comment]
Ok sorry it works perfectly with geoJSON ! 
We must include this documentation in #208 

One format is enough so far, so I close the issue
