### ISSUE TITLE
Draft maps must not be accessible if not connected

### ISSUE THREAD

**Issue by aangelot** [datatlas-erasme/datatlas#220]
With error page 403 for @lutangar

**Comment by lutangar** [comment]
@racine-p-a I can't remember, did we fix this already ?

**Comment by racine-p-a** [comment]
Yep. It's done.

**Comment by racine-p-a** [comment]
Yep. It's done.

**Comment by aangelot** [comment]
I reopen this issue : I still can access maps that are drafts... 
For example this map is not published : https://dev-datatlas.datagora.erasme.org/projects/39 but I can access it not being connected
