### ISSUE TITLE
Cannot see my projects

### ISSUE THREAD

**Issue by aangelot** [datatlas-erasme/datatlas#223]
Test with Firefox on Ubuntu 

**How to reproduce :** 
- connect to datatlas with an editor account 
- the projects must display 
- refreshing the page the projects don't display anymore 

However in the network console GET/projects send a 200 with real projects

It may be a cache problem ?

**Comment by aangelot** [comment]
EDIT : the issue occurs also with an ADMIN account. 

I created a new admin account, connecting with it there is no project. 
However, for the GET/projects request, there are two responses : a 204 (no content) and a 200 (with real data inside) 

As I can't open DatAtlas if new users can't see their projects I priorize this issue @lutangar

**Comment by lutangar** [comment]
@aangelot this feature is now live ! 
https://dev-datatlas.datagora.erasme.org/

> *Remember to clear your cache.*
