### ISSUE TITLE
Modal customization

### ISSUE THREAD

**Issue by lutangar** [datatlas-erasme/datatlas#249]
There are feature request about modal customization with Html.
We probably won't support Html but we might support a few customizations with markdown instead.

**Comment by aangelot** [comment]
Markdown can do the job, let's see with @SeongHunChandra's wireframes what customization is required

**Comment by aangelot** [comment]
@lutangar  you should like this file 

![Image](https://github.com/datatlas-erasme/datatlas/assets/33604381/bb66dcef-6c2b-40e8-a478-45c4b3bb3524)


And this one : https://drive.google.com/file/d/1BUiQsgAK29X6yN_Rl043hHAPRO5AdiAg/view?usp=drive_link (full screen modal)

You can try with this database : https://www.notion.so/erasme/4b37739d2467440289998a816e220bfc?v=7903a4d556934d8d95c969fee0efe89f (with images)

**Comment by lutangar** [comment]
__Tooltip__
- Show 4 first fields in order of appearance (except for an image field which is always hidden)
- Always show label and value except for :
  - image and title, where we only show the formatted value
  - for long text, where the value is cropped with an ellipsis

If there is : 
- a truncated text or
- an image or
- or more than 4 fields

Then show the "show more" button. 

__Modal__

Show all fields in order of appearance  following previous except :
- images are shown
- long text aren't truncated

**Comment by lutangar** [comment]
### Aggregated data

__i18n__

```typescript
export const AGGREGATION_TYPES = {
  // default
  count: 'count',
  // linear
  average: 'average',
  maximum: 'maximum',
  minimum: 'minimum',
  median: 'median',
  stdev: 'stdev',
  sum: 'sum',
  variance: 'variance',
  // ordinal
  mode: 'mode',
  countUnique: 'count unique'
};

// Might not be easy to extract & translate this but we could nonetheless give it try :
const measure = `${aggregation} of ${fieldName}`;
```

`Total points` (cf screenshot)
![Image](https://github.com/datatlas-erasme/datatlas/assets/568769/a65cca58-2493-4d65-97c7-8d74bf647dde)


@aangelot could you suggest translations for these terms & phrases ?

**Comment by lutangar** [comment]
@aangelot about the aggregated layer tooltip : we may also choose to change  the order of appearance of each measure or even radically change the content disposition.

**Comment by aangelot** [comment]
export const AGGREGATION_TYPES = {
  // default
  count: 'Nombre',
  // linear
  average: 'Moyenne',
  maximum: 'Maximum',
  minimum: 'Minimum',
  median: 'Médiane',
  stdev: 'Écart-type',
  sum: 'Somme',
  variance: 'Variance',
  // ordinal
  mode: 'Mode',
  countUnique: 'Compte unique'
};

Total points : 'Nombre d'items'
Mode of groupe : 'Mode du groupe'
Sum of : 'Somme de'

About the tooltip, let's start simply by changing the order of each piece of data, if it's necessary.

**Comment by lutangar** [comment]
Here's the todolist extracted from our last meeting 2 weeks ago and progress so far :

- [ ] Hand cursor on POI hover (probable regression) (edit: nop, just wasn't available in Kepler.gl 2.5)
- [x] Fixed width tooltip 
- [x] Tooltip placement (top-left)
- [x] Remove close button
- [x] Image padding

### Display rules
- [x] Hide "detailed view button" when not necessary
- [x] Add "max fields to show" setting

### Aggregated data 
- [x] Work on tooltip layout
- [ ] i18n (@aangelot should be move to own issue)

### Mobile experience
The overall mobile experience is poor, I'll spend some time today to improve that.
- [x] Touchscreen ?

### Visual design
- [ ] POI detailed view modal
- [ ] Type sizes for different modals

Feel free to edit this list if any points seem to be missing.

**Comment by SeongHunChandra** [comment]
Just added the visual design elements to the todo list

**Comment by lutangar** [comment]
I'm moving this issue to the next step and let you cut this up into smaller pieces as you see fit.

**Comment by aangelot** [comment]
i18n migrate to #306
