### ISSUE TITLE
Can't save big datasets

### ISSUE THREAD

**Issue by aangelot** [datatlas-erasme/datatlas#288]
How to reproduce : 
1. I choose a map and try to add a big dataset from data.grandlyon. For example, trees or bicycle hoops (https://data.grandlyon.com/geoserver/metropole-de-lyon/ows?SERVICE=WFS&VERSION=2.0.0&request=GetFeature&typename=metropole-de-lyon:pvo_patrimoine_voirie.pvostationnementvelo&outputFormat=application/json&SRSNAME=EPSG:4171&sortBy=gid) with mor than 5000 points
2. By adding this dataset, it shows on the map and i can interact with it
3. But if i refresh the page or open the map as a visitor the dataset doesn't show

Desired behaviour : 
Big datasets can be saved in Datatlas projects

cf #166

**Comment by lutangar** [comment]
> Duplicate of #166 

```
PayloadTooLargeError: request entity too large
```

https://grafana.prod.erasme.org/explore?orgId=1&left=%7B%22datasource%22:%223Nycfmk4k%22,%22queries%22:%5B%7B%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%223Nycfmk4k%22%7D,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bjob%3D%5C%22datatlas-dev%2Fbackend%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22refId%22:%22A%22%7D%5D,%22range%22:%7B%22from%22:%221700175600000%22,%22to%22:%221700261999000%22%7D%7D
