### ISSUE TITLE
Track usage of back-office

### ISSUE THREAD

**Issue by lutangar** [datatlas-erasme/datatlas#33]
- [x] Configure matmo tracking Id via env variable.
- [x] Add matomo tracking code snippets.

**Comment by aangelot** [comment]
Just an update before the experimentation I also priorize this issue (It must be just a 1 complexity) 
Just below the code. An advice from Matomo : We recommend placing it immediately before the closing </head> tag.


[Datatlas.txt](https://github.com/datatlas-erasme/datatlas/files/12586287/Datatlas.txt)

**Comment by aangelot** [comment]
There is only one log on Matomo, at 11am on September 26...
But there are no more logs after that, even though I (and not only me) used DatAtlas every day...

**Comment by lutangar** [comment]
Should be fixed by now. You may (re)close this issue if it's the case.

**Comment by aangelot** [comment]
We receive logs from a few days, perfect.
