### ISSUE TITLE
:fr: Internationalisation

### ISSUE THREAD

**Issue by aangelot** [datatlas-erasme/datatlas#71]
:fr:
__Kepler__
- [x] Récupérer le dictionnaire de __Kepler__ en Anglais et le traduire en __Fançais__
   - [x] Le traduire
   - [ ] __BONUS POINT :__  Submit it to __Kepler__ as a PR
     - [ ] Checkout Kepler and test it locally before submitting anything
- [ ] Constituer le dictionnaire de __Datatlas__ à partir des clés existantes dans Datatlas 
   - [ ] Selon la stratégie choisi pour les clés, les traduires en Fr / EN
   > Le standard serait d'avoir la clé en anglais (ou voir une clé technique) puis traduite en français, mais pas le cas actuellement.
> Il existe des outils automatisés pour extraire & MAJ son dico local voir CLI react-intl
- [ ] Vérifier que la locale de __Datatlas__ soit en sync avec la locale de __Kepler__
    - Datatlas est en FR par défault -> alors Kepler en Francais
    - Je change la locale dans Kepler -> Datatlas aussi

**Comment by aangelot** [comment]
Is it the same as #46 ?

**Comment by lutangar** [comment]
> Is it the same as #46 ?

Yes.

**Comment by aangelot** [comment]
Everything looks fine for me, I just have a few questions : 

- was it submit to Kepler ? 
- In the Kepler view, when selecting the language is it possible to replace "toolbar.fr" by "Français" ? cf screenshot 1
- is it possible to translate the basemap style ? cf screenshot 2 Same question for the "start a new project menu" : the name of the basemaps are in english

![Image](https://github.com/datatlas-erasme/datatlas/assets/33604381/491fbbc0-9959-41c9-b8fc-6e8b86a87c61)

![Image](https://github.com/datatlas-erasme/datatlas/assets/33604381/71ebbe2d-970e-440d-903d-362a9c309174)

**Comment by lutangar** [comment]
> was it submit to Kepler ?

No, because it meant extra work. But cnce we're happy with the quality of the translations we may as well propose it.

> In the Kepler view, when selecting the language is it possible to replace "toolbar.fr" by "Français" ? cf screenshot 1
> is it possible to translate the basemap style ? cf screenshot 2 Same question for the "start a new project menu" : the name of the basemaps are in english

Sur let's add these to the todo.

**Comment by lutangar** [comment]
What's your suggestion for the following ? Here's my attempt :
- Dark : Sombre
- Light : Clair
- Light : Clair tamisé
- Muted Night : Nuit tamisé  
- Satellite : Satellite
