### ISSUE TITLE
Design API endpoints

### ISSUE THREAD

**Issue by lutangar** [datatlas-erasme/datatlas#9]
- Add documentation

**Comment by aangelot** [comment]
Reorganize doc and integrate in the project

**Comment by lutangar** [comment]
@racine-p-a could you update project -- backend or main -- README with a few info on the API (at least how to reach the swagger doc ).
I had something like this in my personal, could use some rewrite though : 

> Checklist API
> =============
> - [ ] POST / PUT : should return updated entity
> - [ ] No 500 unless something unexpected or really bad happened
>     - [ ] 4XX otherwise : a user didn't send good enough data ex: a required field is missing, entity doesn't exist, etc.
> - [ ] We should be able to play with __Swagger__ http://localhost:3333/api
>     - [ ] Authent should work there too
